Repository SamCoMo/DBZ-Backend, pull requests merged in 2024-03, with the labels that each got.

#13 refactor : 피드백 반영한 코드 수정
  src/main/java/com/samcomo/dbz/report/controller/ReportController.java
  src/main/java/com/samcomo/dbz/report/model/repository/ReportRepository.java
  src/main/java/com/samcomo/dbz/report/service/ReportService.java
  src/main/java/com/samcomo/dbz/report/service/impl/ReportServiceImpl.java
Labels: bug, server, refacotr

#19 [#17]refactor: baseEntity 설정 변경
  src/main/java/com/samcomo/dbz/DbzApplication.java
  src/main/java/com/samcomo/dbz/global/entity/BaseEntity.java
  src/main/java/com/samcomo/dbz/member/model/entity/Member.java
Labels: server, refactor

#20 Feature/report test
  README.md
  src/main/java/com/samcomo/dbz/global/s3/S3Service.java
  src/main/java/com/samcomo/dbz/report/controller/ReportController.java
  src/main/java/com/samcomo/dbz/report/model/dto/ReportDto.java
  src/main/java/com/samcomo/dbz/report/service/ReportService.java
  src/main/java/com/samcomo/dbz/report/service/impl/ReportServiceImpl.java
  src/main/resources/sql/reportDumy.sql
  src/test/java/com/samcomo/dbz/DbzApplicationTests.java
  src/test/java/com/samcomo/dbz/report/service/ReportServiceTest.java
Labels: help wanted, server, refactor

#26 hotfix: jpa metadata empty 에러
  src/test/java/com/samcomo/dbz/member/controller/MemberControllerTest.java
Labels: bug, server

#28 [Feature/jwt] jwt 자체 로그인 구현
  .gitignore
  build.gradle
  src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java
  src/main/java/com/samcomo/dbz/global/exception/ErrorCode.java
  src/main/java/com/samcomo/dbz/member/model/constants/MemberRole.java
  src/main/java/com/samcomo/dbz/member/model/constants/TokenType.java
  src/main/java/com/samcomo/dbz/member/model/dto/MemberDetails.java
  src/main/java/com/samcomo/dbz/member/model/entity/Member.java
  src/main/java/com/samcomo/dbz/member/model/jwt/JwtUtil.java
  src/main/java/com/samcomo/dbz/member/model/jwt/filter/JwtFilter.java
  src/main/java/com/samcomo/dbz/member/model/jwt/filter/LoginFilter.java
  src/main/java/com/samcomo/dbz/member/service/MemberService.java
  src/main/java/com/samcomo/dbz/member/service/impl/MemberDetailsServiceImpl.java
  src/main/java/com/samcomo/dbz/member/service/impl/MemberServiceImpl.java
  src/main/resources/application.yml
Labels: enhancement, server

#29 refactor: 게시글 리스트 조회 메소드 성능 개선
  build.gradle
  src/main/java/com/samcomo/dbz/DbzApplication.java
  src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java
  src/main/java/com/samcomo/dbz/global/redis/RedisCacheConfig.java
  src/main/java/com/samcomo/dbz/global/redis/RedisConfiguration.java
  src/main/java/com/samcomo/dbz/report/controller/ReportController.java
  src/main/java/com/samcomo/dbz/report/model/dto/CustomPageable.java
  src/main/java/com/samcomo/dbz/report/model/dto/CustomSlice.java
  src/main/java/com/samcomo/dbz/report/model/dto/ReportList.java
  src/main/java/com/samcomo/dbz/report/model/repository/ReportRepository.java
  src/main/java/com/samcomo/dbz/report/service/ReportService.java
  src/main/java/com/samcomo/dbz/report/service/impl/ReportServiceImpl.java
  src/main/resources/application-dev.yml
  src/main/resources/sql/reportDumy.sql
  src/test/java/com/samcomo/dbz/report/service/ReportServiceTest.java
Labels: enhancement, server, refactor

#25 [FEATURE-CHAT]: 채팅 기본 기능 구현
  build.gradle
  src/main/java/com/samcomo/dbz/chat/config/MongoConfig.java
  src/main/java/com/samcomo/dbz/chat/config/WebSocketConfig.java
  src/main/java/com/samcomo/dbz/chat/controller/ChatController.java
  src/main/java/com/samcomo/dbz/chat/dto/ChatMessageDto.java
  src/main/java/com/samcomo/dbz/chat/dto/ChatRoomDto.java
  src/main/java/com/samcomo/dbz/chat/model/entity/ChatImage.java
  src/main/java/com/samcomo/dbz/chat/model/entity/ChatMessage.java
  src/main/java/com/samcomo/dbz/chat/model/entity/ChatRoom.java
  src/main/java/com/samcomo/dbz/chat/model/repository/ChatMessageRepository.java
  src/main/java/com/samcomo/dbz/chat/model/repository/ChatRoomRepository.java
  src/main/java/com/samcomo/dbz/chat/service/ChatRoomService.java
  src/main/java/com/samcomo/dbz/chat/service/ChatService.java
  src/main/java/com/samcomo/dbz/chat/service/impl/ChatRoomServiceImpl.java
  src/main/java/com/samcomo/dbz/chat/service/impl/ChatServiceImpl.java
  src/main/java/com/samcomo/dbz/chat/util/ChatUtils.java
  src/main/java/com/samcomo/dbz/global/exception/ErrorCode.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/test/java/com/samcomo/dbz/chat/service/impl/ChatRoomServiceImplTest.java
  src/test/java/com/samcomo/dbz/chat/service/impl/ChatServiceImplTest.java
  src/test/java/com/samcomo/dbz/member/controller/MemberControllerTest.java
Labels: enhancement

#36 [Refactor/member] member 도메인 리펙토링 & baseEntity 수정
  src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java
  src/main/java/com/samcomo/dbz/global/entity/BaseEntity.java
  src/main/java/com/samcomo/dbz/member/controller/MemberController.java
  src/main/java/com/samcomo/dbz/member/jwt/JwtUtil.java
  src/main/java/com/samcomo/dbz/member/jwt/filter/JwtFilter.java
  src/main/java/com/samcomo/dbz/member/jwt/filter/LoginFilter.java
  src/main/java/com/samcomo/dbz/member/model/constants/MemberRole.java
  src/main/java/com/samcomo/dbz/member/model/dto/MemberDetails.java
  src/main/java/com/samcomo/dbz/member/model/dto/RegisterDto.java
  src/main/java/com/samcomo/dbz/member/model/dto/RegisterRequestDto.java
  src/main/java/com/samcomo/dbz/member/model/entity/Member.java
  src/main/java/com/samcomo/dbz/member/service/MemberService.java
  src/main/java/com/samcomo/dbz/member/service/impl/MemberDetailsServiceImpl.java
  src/main/java/com/samcomo/dbz/member/service/impl/MemberServiceImpl.java
  src/test/java/com/samcomo/dbz/member/controller/MemberControllerTest.java
  src/test/java/com/samcomo/dbz/member/service/impl/MemberServiceImplTest.java
Labels: server, refactor

#34 Feature : Redis Dstributed Lock(분산락)을 사용하여 조회수 에서 발생하는 동시성 이슈 해결
  build.gradle
  src/main/java/com/samcomo/dbz/global/exception/ErrorCode.java
  src/main/java/com/samcomo/dbz/global/redis/RedisConfiguration.java
  src/main/java/com/samcomo/dbz/report/model/repository/ReportRepository.java
  src/main/java/com/samcomo/dbz/report/service/impl/ReportServiceImpl.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/main/resources/sql/reportDumy.sql
  src/test/java/com/samcomo/dbz/report/service/ReportViewTest.java
Labels: enhancement, server

#42 [Refactor/report] S3Service 이미지 업로드 메소드 수정
  src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java
  src/main/java/com/samcomo/dbz/global/redis/LockType.java
  src/main/java/com/samcomo/dbz/global/redis/RedisCacheConfig.java
  src/main/java/com/samcomo/dbz/global/redis/RedisConfiguration.java
  src/main/java/com/samcomo/dbz/global/redis/aop/AopForTransaction.java
  src/main/java/com/samcomo/dbz/global/redis/aop/DistributedLock.java
  src/main/java/com/samcomo/dbz/global/redis/aop/DistributedLockAop.java
  src/main/java/com/samcomo/dbz/global/redis/exception/RedissonException.java
  src/main/java/com/samcomo/dbz/global/s3/service/S3Service.java
  src/main/java/com/samcomo/dbz/report/controller/ReportController.java
  src/main/java/com/samcomo/dbz/report/service/ReportService.java
  src/main/java/com/samcomo/dbz/report/service/impl/ReportServiceImpl.java
  src/main/resources/application.yml
  src/test/java/com/samcomo/dbz/report/service/ReportServiceTest.java
  src/test/java/com/samcomo/dbz/report/service/ReportViewTest.java
Labels: server, refactor

#39 [Feature/register] 회원가입 validation 구현
  .gitignore
  src/main/java/com/samcomo/dbz/global/exception/GlobalExceptionHandler.java
  src/main/java/com/samcomo/dbz/global/utils/EmailValidator.java
  src/main/java/com/samcomo/dbz/global/utils/annotation/EmailCheck.java
  src/main/java/com/samcomo/dbz/member/controller/MemberController.java
  src/main/java/com/samcomo/dbz/member/jwt/filter/JwtFilter.java
  src/main/java/com/samcomo/dbz/member/model/constants/MemberRole.java
  src/main/java/com/samcomo/dbz/member/model/dto/RegisterRequestDto.java
  src/test/java/com/samcomo/dbz/member/controller/MemberControllerTest.java
Labels: enhancement, server

#45 [Refactor/report] 위/경도 파라미터 타입 변경(primitive -> wrapper), Response 파라미터 추가
  src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java
  src/main/java/com/samcomo/dbz/global/exception/ErrorCode.java
  src/main/java/com/samcomo/dbz/global/redis/aop/DistributedLockAop.java
  src/main/java/com/samcomo/dbz/report/controller/ReportController.java
  src/main/java/com/samcomo/dbz/report/model/dto/ReportDto.java
  src/main/java/com/samcomo/dbz/report/model/dto/ReportList.java
  src/main/java/com/samcomo/dbz/report/model/dto/ReportStateDto.java
  src/main/java/com/samcomo/dbz/report/model/entity/Report.java
  src/main/java/com/samcomo/dbz/report/model/repository/ReportRepository.java
  src/main/java/com/samcomo/dbz/report/service/ReportService.java
  src/main/java/com/samcomo/dbz/report/service/impl/ReportServiceImpl.java
  src/test/java/com/samcomo/dbz/report/service/ReportServiceTest.java
  src/test/java/com/samcomo/dbz/report/service/ReportViewTest.java
Labels: server, refactor

#46 [Refactor/dto and entity] 전체적인 Dto, Entity 수정 & 로그인 정보 가져오는 방법 수정
  src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java
  src/main/java/com/samcomo/dbz/report/controller/ReportController.java
  src/main/java/com/samcomo/dbz/report/model/constants/PetType.java
  src/main/java/com/samcomo/dbz/report/model/constants/ReportStatus.java
  src/main/java/com/samcomo/dbz/report/model/dto/CustomPageable.java
  src/main/java/com/samcomo/dbz/report/model/dto/CustomSlice.java
  src/main/java/com/samcomo/dbz/report/model/dto/ReportDto.java
  src/main/java/com/samcomo/dbz/report/model/dto/ReportImageDto.java
  src/main/java/com/samcomo/dbz/report/model/dto/ReportStateDto.java
  src/main/java/com/samcomo/dbz/report/model/dto/ReportSummaryDto.java
  src/main/java/com/samcomo/dbz/report/model/entity/Report.java
  src/main/java/com/samcomo/dbz/report/model/entity/ReportImage.java
  src/main/java/com/samcomo/dbz/report/model/repository/ReportRepository.java
  src/main/java/com/samcomo/dbz/report/service/ReportService.java
  src/main/java/com/samcomo/dbz/report/service/impl/ReportServiceImpl.java
  src/test/java/com/samcomo/dbz/report/service/ReportServiceTest.java
  src/test/java/com/samcomo/dbz/report/service/ReportViewTest.java
Labels: server, refactor

#49 [Hotfix/Report] 게시글 삭제 불가 해결
  src/main/java/com/samcomo/dbz/global/s3/service/S3Service.java
  src/main/java/com/samcomo/dbz/report/model/entity/ReportImage.java
  src/main/java/com/samcomo/dbz/report/model/repository/ReportImageRepository.java
  src/main/java/com/samcomo/dbz/report/service/impl/ReportServiceImpl.java
Labels: bug, server, refactor

#44 [FEATURE/PIN]: PIN기능 기본 CRUD 구현
  src/main/java/com/samcomo/dbz/chat/controller/ChatController.java
  src/main/java/com/samcomo/dbz/chat/dto/ChatMessageDto.java
  src/main/java/com/samcomo/dbz/chat/dto/ChatRoomDto.java
  src/main/java/com/samcomo/dbz/chat/service/impl/ChatRoomServiceImpl.java
  src/main/java/com/samcomo/dbz/chat/util/ChatUtils.java
  src/main/java/com/samcomo/dbz/global/exception/ErrorCode.java
  src/main/java/com/samcomo/dbz/global/s3/constants/ImageCategory.java
  src/main/java/com/samcomo/dbz/pin/controller/PinController.java
  src/main/java/com/samcomo/dbz/pin/dto/CreatePinDto.java
  src/main/java/com/samcomo/dbz/pin/dto/PinImageDto.java
  src/main/java/com/samcomo/dbz/pin/dto/UpdatePinAddressDto.java
  src/main/java/com/samcomo/dbz/pin/dto/UpdatePinDataDto.java
  src/main/java/com/samcomo/dbz/pin/model/entity/Pin.java
  src/main/java/com/samcomo/dbz/pin/model/entity/PinImage.java
  src/main/java/com/samcomo/dbz/pin/model/repository/PinImageRepository.java
  src/main/java/com/samcomo/dbz/pin/model/repository/PinRepository.java
  src/main/java/com/samcomo/dbz/pin/service/PinService.java
  src/main/java/com/samcomo/dbz/pin/service/impl/PinServiceImpl.java
  src/main/java/com/samcomo/dbz/pin/util/PinUtils.java
  src/main/resources/application-dev.yml
Labels: documentation, refactor

#50 [Feature/Notification] 핀 등록시 알림 전송
  .gitignore
  build.gradle
  src/main/java/com/samcomo/dbz/global/exception/ErrorCode.java
  src/main/java/com/samcomo/dbz/global/firebase/FCMConfig.java
  src/main/java/com/samcomo/dbz/notification/controller/FcmController.java
  src/main/java/com/samcomo/dbz/notification/exception/NotiException.java
  src/main/java/com/samcomo/dbz/notification/model/dto/FcmMessageDto.java
  src/main/java/com/samcomo/dbz/notification/model/dto/SendPinDto.java
  src/main/java/com/samcomo/dbz/notification/service/FcmService.java
  src/main/java/com/samcomo/dbz/notification/service/FcmServiceImpl.java
  src/main/resources/application-dev.yml
Labels: enhancement, server

#64 [Refactor/member] jwt 토큰 페이로드 정보 변경
  src/main/java/com/samcomo/dbz/member/jwt/JwtUtil.java
  src/main/java/com/samcomo/dbz/member/jwt/filter/JwtFilter.java
  src/main/java/com/samcomo/dbz/member/jwt/filter/LoginFilter.java
  src/main/java/com/samcomo/dbz/member/model/dto/MemberDetails.java
  src/main/java/com/samcomo/dbz/report/controller/ReportController.java
  src/main/java/com/samcomo/dbz/report/model/repository/ReportRepository.java
  src/main/java/com/samcomo/dbz/report/service/ReportService.java
  src/main/java/com/samcomo/dbz/report/service/impl/ReportServiceImpl.java
  src/test/java/com/samcomo/dbz/report/service/ReportServiceTest.java
  src/test/java/com/samcomo/dbz/report/service/ReportViewTest.java
Labels: server, refactor

#65 [Refactor/pin] 핀 전체적인 리펙터링
  src/main/java/com/samcomo/dbz/member/jwt/JwtUtil.java
  src/main/java/com/samcomo/dbz/member/jwt/filter/JwtFilter.java
  src/main/java/com/samcomo/dbz/member/jwt/filter/LoginFilter.java
  src/main/java/com/samcomo/dbz/pin/controller/PinController.java
  src/main/java/com/samcomo/dbz/pin/dto/PinImageDto.java
  src/main/java/com/samcomo/dbz/pin/dto/RegisterPinDto.java
  src/main/java/com/samcomo/dbz/pin/dto/UpdatePinAddressDto.java
  src/main/java/com/samcomo/dbz/pin/dto/UpdatePinDto.java
  src/main/java/com/samcomo/dbz/pin/model/entity/Pin.java
  src/main/java/com/samcomo/dbz/pin/model/entity/PinImage.java
  src/main/java/com/samcomo/dbz/pin/model/repository/PinImageRepository.java
  src/main/java/com/samcomo/dbz/pin/model/repository/PinRepository.java
  src/main/java/com/samcomo/dbz/pin/service/PinService.java
  src/main/java/com/samcomo/dbz/pin/service/impl/PinServiceImpl.java
  src/main/java/com/samcomo/dbz/pin/util/PinUtils.java
Labels: server, refactor

#68 [Feat/member] 마이페이지 구현
  build.gradle
  src/main/java/com/samcomo/dbz/member/controller/MemberController.java
  src/main/java/com/samcomo/dbz/member/model/dto/MemberMyInfo.java
  src/main/java/com/samcomo/dbz/member/service/MemberService.java
  src/main/java/com/samcomo/dbz/member/service/impl/MemberServiceImpl.java
Labels: enhancement, server

#70 [Feature/reissue(RTR)] RTR 방식의 jwt 토큰 재발급 구현
  src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java
  src/main/java/com/samcomo/dbz/global/exception/ErrorCode.java
  src/main/java/com/samcomo/dbz/member/controller/MemberController.java
  src/main/java/com/samcomo/dbz/member/jwt/JwtUtil.java
  src/main/java/com/samcomo/dbz/member/jwt/filter/AccessTokenFilter.java
  src/main/java/com/samcomo/dbz/member/jwt/filter/LoginFilter.java
  src/main/java/com/samcomo/dbz/member/jwt/filter/RefreshTokenFilter.java
  src/main/java/com/samcomo/dbz/member/model/constants/TokenType.java
  src/main/java/com/samcomo/dbz/member/model/dto/RegisterRequestDto.java
  src/main/java/com/samcomo/dbz/member/model/entity/RefreshToken.java
  src/main/java/com/samcomo/dbz/member/model/repository/RefreshTokenRepository.java
Labels: enhancement, server

#72 [Feature/member] WithMockMember 어노테이션 구현
  src/main/java/com/samcomo/dbz/report/controller/ReportController.java
  src/test/java/com/samcomo/dbz/member/controller/MemberControllerTest.java
  src/test/java/com/samcomo/dbz/report/controller/ReportControllerTest.java
  src/test/java/com/samcomo/dbz/utils/WithMemberSecurityContextFactory.java
  src/test/java/com/samcomo/dbz/utils/annotation/WithMockMember.java
Labels: enhancement, refactor

#77 [Refactor/Report] Actuator추가, Response에 wrtierId 추가, 테스트코드 수정
  build.gradle
  src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java
  src/main/java/com/samcomo/dbz/report/model/dto/ReportDto.java
  src/main/java/com/samcomo/dbz/report/model/dto/ReportSummaryDto.java
  src/main/java/com/samcomo/dbz/report/model/repository/ReportBulkRepository.java
  src/main/java/com/samcomo/dbz/report/service/impl/ReportServiceImpl.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/test/java/com/samcomo/dbz/report/controller/ReportControllerTest.java
  src/test/java/com/samcomo/dbz/report/service/ReportServiceTest.java
Labels: enhancement, server, refactor

#75 [Feature/member] 회원 위치정보 업데이트
  src/main/java/com/samcomo/dbz/member/controller/MemberController.java
  src/main/java/com/samcomo/dbz/member/model/dto/LocationUpdateRequest.java
  src/main/java/com/samcomo/dbz/member/model/dto/MyPageResponse.java
  src/main/java/com/samcomo/dbz/member/model/dto/RegisterRequest.java
  src/main/java/com/samcomo/dbz/member/model/entity/Member.java
  src/main/java/com/samcomo/dbz/member/model/repository/MemberRepository.java
  src/main/java/com/samcomo/dbz/member/service/MemberService.java
  src/main/java/com/samcomo/dbz/member/service/impl/MemberServiceImpl.java
  src/test/java/com/samcomo/dbz/member/controller/MemberControllerTest.java
  src/test/java/com/samcomo/dbz/member/service/impl/MemberServiceImplTest.java
Labels: enhancement, server

#73 [Refactor/jwt-filter] Filter 클래스의 객체지향적인 코드 설계
  src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java
  src/main/java/com/samcomo/dbz/global/exception/ErrorCode.java
  src/main/java/com/samcomo/dbz/member/controller/MemberController.java
  src/main/java/com/samcomo/dbz/member/jwt/JwtUtil.java
  src/main/java/com/samcomo/dbz/member/jwt/filter/AccessTokenFilter.java
  src/main/java/com/samcomo/dbz/member/jwt/filter/FilterMemberExceptionHandler.java
  src/main/java/com/samcomo/dbz/member/jwt/filter/RefreshTokenFilter.java
  src/main/java/com/samcomo/dbz/member/model/dto/MemberDetails.java
Labels: server, refactor

#74 [Feature/logout] 필터를 이용한 로그아웃 구현
  src/main/java/com/samcomo/dbz/chat/config/WebSocketConfig.java
  src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java
  src/main/java/com/samcomo/dbz/global/exception/ErrorCode.java
  src/main/java/com/samcomo/dbz/member/jwt/JwtUtil.java
  src/main/java/com/samcomo/dbz/member/jwt/filter/AccessTokenFilter.java
  src/main/java/com/samcomo/dbz/member/jwt/filter/CustomLoginFilter.java
  src/main/java/com/samcomo/dbz/member/jwt/filter/CustomLogoutFilter.java
  src/main/java/com/samcomo/dbz/member/jwt/filter/RefreshTokenFilter.java
  src/main/java/com/samcomo/dbz/member/model/repository/RefreshTokenRepository.java
Labels: enhancement, server, refactor

#84 [Refactor/chat] 채팅 전체 리펙터링 & 컨벤션
  src/main/java/com/samcomo/dbz/chat/config/WebSocketConfig.java
  src/main/java/com/samcomo/dbz/chat/controller/ChatController.java
  src/main/java/com/samcomo/dbz/chat/model/dto/ChatMessageDto.java
  src/main/java/com/samcomo/dbz/chat/model/dto/ChatRoomDto.java
  src/main/java/com/samcomo/dbz/chat/model/entity/ChatMessage.java
  src/main/java/com/samcomo/dbz/chat/model/entity/ChatRoom.java
  src/main/java/com/samcomo/dbz/chat/model/repository/ChatMessageRepository.java
  src/main/java/com/samcomo/dbz/chat/service/ChatRoomService.java
  src/main/java/com/samcomo/dbz/chat/service/ChatService.java
  src/main/java/com/samcomo/dbz/chat/service/impl/ChatRoomServiceImpl.java
  src/main/java/com/samcomo/dbz/chat/service/impl/ChatServiceImpl.java
  src/main/java/com/samcomo/dbz/chat/util/ChatUtils.java
  src/main/java/com/samcomo/dbz/member/model/dto/MemberDetails.java
  src/main/java/com/samcomo/dbz/report/model/dto/CustomSlice.java
  src/main/java/com/samcomo/dbz/report/model/dto/ReportDto.java
Labels: server, refactor

#85 [Refactor/Security] security cors 설정 추가
  src/main/java/com/samcomo/dbz/global/config/CorsMvcConfig.java
  src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java
  src/main/java/com/samcomo/dbz/notification/service/NotificationService.java
  src/main/java/com/samcomo/dbz/notification/service/NotificationServiceImpl.java
  src/main/java/com/samcomo/dbz/report/model/entity/Report.java
  src/main/java/com/samcomo/dbz/report/service/impl/ReportServiceImpl.java
Labels: server, refactor

#86 [Feature/member] 로그인 시 fcmToken 업데이트
  src/main/java/com/samcomo/dbz/chat/config/WebSocketConfig.java
  src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java
  src/main/java/com/samcomo/dbz/member/jwt/filter/CustomLoginFilter.java
  src/main/java/com/samcomo/dbz/member/model/entity/Member.java
Labels: enhancement, server

#92 [Refactor/global] global 컨벤션
  src/main/java/com/samcomo/dbz/chat/config/WebSocketConfig.java
  src/main/java/com/samcomo/dbz/chat/controller/ChatController.java
  src/main/java/com/samcomo/dbz/global/config/CorsMvcConfig.java
  src/main/java/com/samcomo/dbz/global/exception/CustomException.java
  src/main/java/com/samcomo/dbz/global/exception/dto/ErrorResponse.java
  src/main/java/com/samcomo/dbz/global/redis/LockType.java
  src/main/java/com/samcomo/dbz/global/redis/RedisConfiguration.java
  src/main/java/com/samcomo/dbz/global/redis/aop/AopForTransaction.java
  src/main/java/com/samcomo/dbz/global/redis/aop/DistributedLock.java
  src/main/java/com/samcomo/dbz/global/redis/aop/DistributedLockAop.java
  src/main/java/com/samcomo/dbz/global/s3/constants/ImageFileType.java
  src/main/java/com/samcomo/dbz/global/s3/constants/ImageUploadState.java
  src/main/java/com/samcomo/dbz/global/s3/service/S3Service.java
  src/main/java/com/samcomo/dbz/member/controller/MemberController.java
  src/main/java/com/samcomo/dbz/member/jwt/JwtUtil.java
  src/main/java/com/samcomo/dbz/member/model/constants/TokenType.java
  src/main/java/com/samcomo/dbz/member/model/dto/TokenValidationResponse.java
Labels: server, refactor

#95 [Fix/Local-Error] 커밋 중복 현상 해결
  src/main/java/com/samcomo/dbz/member/jwt/JwtUtil.java
Labels: bug

#99 [Fix/cookie] 쿠키 sameSite 오류
  src/main/java/com/samcomo/dbz/member/jwt/filter/CustomLoginFilter.java
  src/main/java/com/samcomo/dbz/member/jwt/filter/RefreshTokenFilter.java
Labels: bug, server

#102 [Refactor/member] 필터 리펙터링 및 쿠키관리용 util 구현
  src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java
  src/main/java/com/samcomo/dbz/global/exception/ErrorCode.java
  src/main/java/com/samcomo/dbz/member/jwt/AuthUtils.java
  src/main/java/com/samcomo/dbz/member/jwt/CookieUtil.java
  src/main/java/com/samcomo/dbz/member/jwt/JwtUtil.java
  src/main/java/com/samcomo/dbz/member/jwt/filter/CustomLoginFilter.java
  src/main/java/com/samcomo/dbz/member/jwt/filter/CustomLogoutFilter.java
  src/main/java/com/samcomo/dbz/member/jwt/filter/RefreshTokenFilter.java
  src/main/java/com/samcomo/dbz/member/model/constants/TokenType.java
Labels: server, refactor

#103 test: access 1분으로 설정 [reissue 태스트용]
  src/main/java/com/samcomo/dbz/member/model/constants/TokenType.java
Labels: server

#104 test: refresh 1분으로 설정
  src/main/java/com/samcomo/dbz/member/model/constants/TokenType.java
Labels: server

#105 [Test/reissue] 액세스, 리프레시 토큰 만료 테스트 완료
  src/main/java/com/samcomo/dbz/member/model/constants/TokenType.java
Labels: server

#106 [Main -> Develop] 동기화
  src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java
  src/main/java/com/samcomo/dbz/global/exception/ErrorCode.java
  src/main/java/com/samcomo/dbz/member/jwt/AuthUtils.java
  src/main/java/com/samcomo/dbz/member/jwt/CookieUtil.java
  src/main/java/com/samcomo/dbz/member/jwt/JwtUtil.java
  src/main/java/com/samcomo/dbz/member/jwt/filter/CustomLoginFilter.java
  src/main/java/com/samcomo/dbz/member/jwt/filter/CustomLogoutFilter.java
  src/main/java/com/samcomo/dbz/member/jwt/filter/RefreshTokenFilter.java
  src/main/java/com/samcomo/dbz/member/model/constants/TokenType.java
  src/main/java/com/samcomo/dbz/report/controller/ReportController.java
  src/main/java/com/samcomo/dbz/report/model/dto/ReportDto.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: server

#98 refactor: 메서드 분리 & 정적 팩터리 패턴 & 컨벤션
  src/main/java/com/samcomo/dbz/chat/controller/ChatController.java
  src/main/java/com/samcomo/dbz/global/exception/ErrorCode.java
  src/main/java/com/samcomo/dbz/member/controller/MemberController.java
  src/main/java/com/samcomo/dbz/notification/controller/NotificationController.java
  src/main/java/com/samcomo/dbz/notification/exception/NotiException.java
  src/main/java/com/samcomo/dbz/notification/model/dto/FcmMessageDto.java
  src/main/java/com/samcomo/dbz/notification/model/dto/NotificationDto.java
  src/main/java/com/samcomo/dbz/notification/model/dto/SendChatDto.java
  src/main/java/com/samcomo/dbz/notification/model/dto/SendPinDto.java
  src/main/java/com/samcomo/dbz/notification/model/dto/SendReportDto.java
  src/main/java/com/samcomo/dbz/notification/model/dto/SendSingleDto.java
  src/main/java/com/samcomo/dbz/notification/model/entity/Notification.java
  src/main/java/com/samcomo/dbz/notification/model/repository/NotifiRepository.java
  src/main/java/com/samcomo/dbz/notification/service/NotificationService.java
  src/main/java/com/samcomo/dbz/notification/service/NotificationServiceImpl.java
  src/main/java/com/samcomo/dbz/report/service/impl/ReportServiceImpl.java
Labels: server, refactor

#107 Feature/update profile image
  src/main/java/com/samcomo/dbz/global/exception/ErrorCode.java
  src/main/java/com/samcomo/dbz/global/s3/constants/ImageCategory.java
  src/main/java/com/samcomo/dbz/global/s3/service/S3Service.java
  src/main/java/com/samcomo/dbz/member/controller/MemberController.java
  src/main/java/com/samcomo/dbz/member/model/dto/LocationRequest.java
  src/main/java/com/samcomo/dbz/member/model/entity/Member.java
  src/main/java/com/samcomo/dbz/member/service/MemberService.java
  src/main/java/com/samcomo/dbz/member/service/impl/MemberServiceImpl.java
  src/test/java/com/samcomo/dbz/member/controller/MemberControllerTest.java
  src/test/java/com/samcomo/dbz/member/service/impl/MemberServiceImplTest.java
Labels: enhancement, server

#108 merge develop to main
  .gitignore
  src/main/java/com/samcomo/dbz/chat/controller/ChatController.java
  src/main/java/com/samcomo/dbz/global/exception/ErrorCode.java
  src/main/java/com/samcomo/dbz/global/s3/constants/ImageCategory.java
  src/main/java/com/samcomo/dbz/global/s3/service/S3Service.java
  src/main/java/com/samcomo/dbz/member/controller/MemberController.java
  src/main/java/com/samcomo/dbz/member/model/dto/LocationRequest.java
  src/main/java/com/samcomo/dbz/member/model/entity/Member.java
  src/main/java/com/samcomo/dbz/member/service/MemberService.java
  src/main/java/com/samcomo/dbz/member/service/impl/MemberServiceImpl.java
  src/main/java/com/samcomo/dbz/notification/controller/NotificationController.java
  src/main/java/com/samcomo/dbz/notification/exception/NotiException.java
  src/main/java/com/samcomo/dbz/notification/model/dto/FcmMessageDto.java
  src/main/java/com/samcomo/dbz/notification/model/dto/NotificationDto.java
  src/main/java/com/samcomo/dbz/notification/model/dto/SendChatDto.java
  src/main/java/com/samcomo/dbz/notification/model/dto/SendPinDto.java
  src/main/java/com/samcomo/dbz/notification/model/dto/SendReportDto.java
  src/main/java/com/samcomo/dbz/notification/model/dto/SendSingleDto.java
  src/main/java/com/samcomo/dbz/notification/model/entity/Notification.java
  src/main/java/com/samcomo/dbz/notification/model/repository/NotifiRepository.java
  src/main/java/com/samcomo/dbz/notification/service/NotificationService.java
  src/main/java/com/samcomo/dbz/notification/service/NotificationServiceImpl.java
  src/main/java/com/samcomo/dbz/report/service/impl/ReportServiceImpl.java
  src/test/java/com/samcomo/dbz/member/controller/MemberControllerTest.java
  src/test/java/com/samcomo/dbz/member/service/impl/MemberServiceImplTest.java
Labels: server

#111 [Feat/member] 회원가입 시 회원 위치정보 저장
  src/main/java/com/samcomo/dbz/member/model/dto/RegisterRequest.java
  src/main/java/com/samcomo/dbz/member/model/entity/Member.java
  src/test/java/com/samcomo/dbz/member/controller/MemberControllerTest.java
  src/test/java/com/samcomo/dbz/member/service/impl/MemberServiceImplTest.java
Labels: enhancement, server

#117 [Fix/member] 회원가입 시 주소받기 보류
  src/main/java/com/samcomo/dbz/member/model/dto/RegisterRequest.java
Labels: server

#119 [Hotfix/pin] 핀 등록 시 목격시간 foundAt 삭제
  src/main/java/com/samcomo/dbz/pin/controller/PinController.java
  src/main/java/com/samcomo/dbz/pin/dto/PinDto.java
  src/main/java/com/samcomo/dbz/pin/dto/PinImageDto.java
  src/main/java/com/samcomo/dbz/pin/dto/PinListDto.java
  src/main/java/com/samcomo/dbz/pin/dto/RegisterPinDto.java
  src/main/java/com/samcomo/dbz/pin/dto/UpdatePinDto.java
  src/main/java/com/samcomo/dbz/pin/model/entity/Pin.java
  src/main/java/com/samcomo/dbz/pin/service/impl/PinServiceImpl.java
  src/main/java/com/samcomo/dbz/pin/util/PinUtils.java
Labels: server

#121 [Feature/member] 소셜 로그인 실패 핸들러 추가
  src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java
  src/main/java/com/samcomo/dbz/global/exception/ErrorCode.java
  src/main/java/com/samcomo/dbz/member/jwt/AuthUtils.java
  src/main/java/com/samcomo/dbz/member/jwt/CookieUtil.java
  src/main/java/com/samcomo/dbz/member/jwt/JwtUtil.java
  src/main/java/com/samcomo/dbz/member/jwt/filter/AccessTokenFilter.java
  src/main/java/com/samcomo/dbz/member/jwt/filter/CustomLoginFilter.java
  src/main/java/com/samcomo/dbz/member/jwt/filter/CustomLogoutFilter.java
  src/main/java/com/samcomo/dbz/member/jwt/filter/RefreshTokenFilter.java
  src/main/java/com/samcomo/dbz/member/jwt/filter/handler/LoginSuccessHandler.java
  src/main/java/com/samcomo/dbz/member/jwt/filter/handler/Oauth2LoginFailureHandler.java
  src/main/java/com/samcomo/dbz/member/model/constants/ParameterKey.java
  src/main/java/com/samcomo/dbz/member/model/constants/UriKey.java
  src/main/java/com/samcomo/dbz/member/model/dto/oauth2/GoogleResponse.java
Labels: enhancement, server
